#!/usr/bin/env python3
"""
Attribute every byte of a built chunk to the source module it came from, and
total the critical path of a channel cold load.

Written for wayfinder ticket #1243 ("what comes off the cold-load critical
path?") so that every child of the navigation epic states its before/after in
the same units, measured the same way. Bytes are exact, so unlike the epic's
time targets there is no noise floor to hide behind.

Method
------
`vite build --sourcemap` emits a `.map` next to each chunk. Walking the
mappings gives, for every generated byte range, the source file it was
compiled from. Summing per source yields a raw-byte breakdown of a chunk by
npm package and by our own module. Gzip is reported for whole files only
(there is no per-module gzip: compression is global to the chunk), so a
per-bucket gzip figure is an estimate at the chunk's own ratio, and is
labelled as such wherever it is quoted.

The critical path of a channel cold load is the entry chunk's static import
closure, plus the `channels/Show.vue` page chunk and its closure, plus the CSS
entry, plus the fonts the document preloads or renders.

Usage
-----
Build with sourcemaps first, from the container (node_modules ships
linux-arm64 bindings, a host run fails):

    docker compose run --rm --no-deps laravel.test bash -lc "npm run build -- --sourcemap"

then, from the repo root:

    python3 cold-load-attribution/attribute.py            # critical-path total
    python3 cold-load-attribution/attribute.py --chunk resources/js/app.ts
    python3 cold-load-attribution/attribute.py --chunk resources/js/pages/channels/Show.vue

Rebuild without `--sourcemap` afterwards: the maps are several MB and the
browser suite's stale-bundle guard reads `public/build`.
"""

from __future__ import annotations

import argparse
import collections
import gzip
import json
import os
import re
import sys

BUILD = "public/build"
B64 = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/"
INDEX = {c: i for i, c in enumerate(B64)}


def decode_vlq(segment: str) -> list[int]:
    """Base64 VLQ, the sourcemap mapping encoding."""
    out, shift, value = [], 0, 0
    for char in segment:
        digit = INDEX[char]
        keep_going = digit & 32
        value += (digit & 31) << shift
        shift += 5
        if not keep_going:
            negative = value & 1
            value >>= 1
            out.append(-value if negative else value)
            value, shift = 0, 0
    return out


def attribute(js_path: str) -> tuple[collections.Counter, int]:
    """Raw generated bytes per source file for one built chunk."""
    code = open(js_path, encoding="utf8", errors="replace").read()
    lines = code.split("\n")
    sourcemap = json.load(open(js_path + ".map"))
    sources = sourcemap["sources"]

    source_index = 0
    per_source: collections.Counter = collections.Counter()

    for line_number, line in enumerate(sourcemap["mappings"].split(";")):
        column = 0
        segments = []
        for segment in (s for s in line.split(",") if s):
            fields = decode_vlq(segment)
            column += fields[0]
            if len(fields) >= 4:
                source_index += fields[1]
                segments.append((column, source_index))
            else:
                segments.append((column, None))

        line_length = len(lines[line_number]) if line_number < len(lines) else 0
        for i, (start, source) in enumerate(segments):
            end = segments[i + 1][0] if i + 1 < len(segments) else line_length
            if source is not None and end > start:
                per_source[sources[source]] += end - start

    return per_source, len(code)


def bucket(source: str) -> str:
    """An npm package name, or our own path relative to the repo root."""
    source = source.replace("\x00", "")
    if "node_modules/" in source:
        parts = source.split("node_modules/")[-1].split("/")
        return "npm:" + ("/".join(parts[:2]) if parts[0].startswith("@") else parts[0])
    return re.sub(r"^.*?/(resources/js/)", r"\1", source)


def gzipped(file_name: str) -> int:
    return len(gzip.compress(open(os.path.join(BUILD, file_name), "rb").read(), 6))


def closure(manifest: dict, key: str, seen: set | None = None) -> set:
    """A manifest key plus everything it statically imports, transitively."""
    seen = set() if seen is None else seen
    if key in seen:
        return seen
    seen.add(key)
    for imported in manifest[key].get("imports", []):
        closure(manifest, imported, seen)
    return seen


def report_chunk(manifest: dict, key: str) -> None:
    entry = manifest[key]
    path = os.path.join(BUILD, entry["file"])
    if not os.path.exists(path + ".map"):
        sys.exit(f"No sourcemap for {entry['file']}. Rebuild with --sourcemap.")

    per_source, total = attribute(path)
    grouped: collections.Counter = collections.Counter()
    for source, size in per_source.items():
        grouped[bucket(source)] += size

    ratio = total / gzipped(entry["file"])
    accounted = sum(grouped.values())
    print(f"{key} -> {entry['file']}")
    print(
        f"  {total / 1024:.0f}K raw / {gzipped(entry['file']) / 1024:.0f}K gz"
        f" (ratio {ratio:.2f}), attributed {accounted / total * 100:.0f}%\n"
    )
    for name, size in grouped.most_common(60):
        print(f"  {size / 1024:8.1f}K raw  ~{size / 1024 / ratio:6.1f}K gz est  {name}")


def report_critical_path(manifest: dict) -> None:
    keys = (
        closure(manifest, "resources/js/app.ts")
        | closure(manifest, "resources/css/app.css")
        | closure(manifest, "resources/js/pages/channels/Show.vue")
    )
    code = sum(gzipped(manifest[k]["file"]) for k in keys)
    code += sum(gzipped(c) for k in keys for c in manifest[k].get("css", []))

    fonts = [v["file"] for v in manifest.values() if "woff" in v["file"]]
    woff2 = sum(gzipped(f) for f in fonts if f.endswith(".woff2"))
    woff = sum(gzipped(f) for f in fonts if f.endswith(".woff"))

    print("Channel cold load, critical path (local gzip -6)")
    print(f"  JS + CSS          {code / 1024:7.1f}K  over {len(keys)} chunks")
    print(f"  fonts .woff2      {woff2 / 1024:7.1f}K")
    print(f"  fonts .woff       {woff / 1024:7.1f}K")
    print(f"  TOTAL             {(code + woff2 + woff) / 1024:7.1f}K")
    print("\n  Budget is 550K wire (#1236). Local gzip -6 runs ~6% above the")
    print("  demo's wire bytes, so compare deltas rather than absolutes.")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--chunk", help="manifest key to break down, e.g. resources/js/app.ts")
    args = parser.parse_args()

    manifest = json.load(open(os.path.join(BUILD, "manifest.json")))
    if args.chunk:
        report_chunk(manifest, args.chunk)
    else:
        report_critical_path(manifest)


if __name__ == "__main__":
    main()
